const db = connect("mongodb://localhost:27017/travelagency");

db.tours.deleteMany({});

// ── Insert Travel Agents ────────────────────────────────────────
db.users.deleteMany({ role: "TRAVEL_AGENT" });

const agents = db.users.insertMany([
  {
    firstName: "Tyrone",
    lastName: "Boyer",
    email: "tyroneboyer@gmail.com",
    passwordHash: "$2a$12$dummyhashforseeding1234567890abcdef",
    role: "TRAVEL_AGENT",
    phone: "480-221-1885",
    messengerLink: "Messenger",
    failedLoginAttempts: 0,
    lockedUntil: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    firstName: "Sarah",
    lastName: "Mitchell",
    email: "sarah.mitchell@travelagency.com",
    passwordHash: "$2a$12$dummyhashforseeding1234567890abcdef",
    role: "TRAVEL_AGENT",
    phone: "312-555-0198",
    messengerLink: "WhatsApp",
    failedLoginAttempts: 0,
    lockedUntil: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    firstName: "Marco",
    lastName: "Rossi",
    email: "marco.rossi@travelagency.com",
    passwordHash: "$2a$12$dummyhashforseeding1234567890abcdef",
    role: "TRAVEL_AGENT",
    phone: "+39-06-555-1234",
    messengerLink: "Telegram",
    failedLoginAttempts: 0,
    lockedUntil: null,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]);

const agentIds = Object.values(agents.insertedIds);
print("✅ Inserted " + agentIds.length + " travel agents");

// ── Insert Tours ────────────────────────────────────────────────
// Meal plan codes: BB = Bed & Breakfast, HB = Half Board, FB = Full Board, AI = All Inclusive, RO = Room Only

db.tours.insertMany([
  {
    name: "Paris City Escape",
    destination: "Paris",
    summary: "Discover the romance of Paris with iconic landmarks, world-class cuisine, and breathtaking art. Walk along the Seine, visit the Eiffel Tower, and explore the Louvre.",
    imageUrls: ["https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800"],
    rating: 4.8,
    reviewCount: 142,
    startDates: [new Date("2026-06-01"), new Date("2026-07-01"), new Date("2026-08-01")],
    durations: ["5 days", "7 days"],
    pricePerDuration: { "5 days": "$999", "7 days": "$1299" },
    mealPlans: ["BB", "HB"],
    mealSupplementsPerDay: { "HB": "$35" },
    tourType: "Cruises",
    hotelName: "Hotel Le Marais",
    hotelDescription: "A charming boutique hotel in the heart of Paris near major attractions.",
    accommodation: "4-star Hotel",
    customDetails: { "Visa Required": "Yes", "Language": "French" },
    guestQuantity: { adultsMaxValue: 4, childrenMaxValue: 2, totalMaxValue: 6 },
    totalCapacity: 30,
    bookedCount: 8,
    freeCancellationDaysBefore: 7,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Bali Tropical Retreat",
    destination: "Bali",
    summary: "Immerse yourself in Bali's lush landscapes, ancient temples, and vibrant culture. Enjoy surfing, spa treatments, and stunning rice terraces in Ubud.",
    imageUrls: ["https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800"],
    rating: 4.9,
    reviewCount: 231,
    startDates: [new Date("2026-06-15"), new Date("2026-07-15"), new Date("2026-09-01")],
    durations: ["7 days", "10 days"],
    pricePerDuration: { "7 days": "$1199", "10 days": "$1599" },
    mealPlans: ["BB", "AI"],
    mealSupplementsPerDay: { "AI": "$55" },
    tourType: "Resorts",
    hotelName: "Ubud Jungle Resort",
    hotelDescription: "Luxury resort nestled in the jungle with private villas and infinity pools.",
    accommodation: "5-star Resort",
    customDetails: { "Visa Required": "On Arrival", "Language": "Balinese/Indonesian" },
    guestQuantity: { adultsMaxValue: 2, childrenMaxValue: 2, totalMaxValue: 4 },
    totalCapacity: 20,
    bookedCount: 5,
    freeCancellationDaysBefore: 10,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Rome & Vatican Tour",
    destination: "Rome",
    summary: "Walk through 3,000 years of history in Rome. Visit the Colosseum, Vatican City, Sistine Chapel, and toss a coin in the Trevi Fountain.",
    imageUrls: ["https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800"],
    rating: 4.7,
    reviewCount: 189,
    startDates: [new Date("2026-05-20"), new Date("2026-06-20"), new Date("2026-09-10")],
    durations: ["5 days", "8 days"],
    pricePerDuration: { "5 days": "$899", "8 days": "$1350" },
    mealPlans: ["BB", "HB"],
    mealSupplementsPerDay: { "HB": "$30" },
    tourType: "Cruises",
    hotelName: "Palazzo Roma Hotel",
    hotelDescription: "Historic palace converted into a modern hotel near the Pantheon.",
    accommodation: "4-star Hotel",
    customDetails: { "Visa Required": "Schengen", "Language": "Italian" },
    guestQuantity: { adultsMaxValue: 4, childrenMaxValue: 2, totalMaxValue: 6 },
    totalCapacity: 25,
    bookedCount: 12,
    freeCancellationDaysBefore: 5,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Dubai Luxury Experience",
    destination: "Dubai",
    summary: "Experience the ultra-modern marvel of Dubai — from Burj Khalifa to desert safaris, luxury malls, and spectacular fountain shows.",
    imageUrls: ["https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800"],
    rating: 4.6,
    reviewCount: 175,
    startDates: [new Date("2026-11-01"), new Date("2026-12-01"), new Date("2027-01-15")],
    durations: ["5 days", "7 days"],
    pricePerDuration: { "5 days": "$1499", "7 days": "$1999" },
    mealPlans: ["BB", "HB", "AI"],
    mealSupplementsPerDay: { "HB": "$50", "AI": "$90" },
    tourType: "Resorts",
    hotelName: "Burj Al Arab Adjacent Suites",
    hotelDescription: "5-star luxury hotel offering panoramic views of the Arabian Gulf.",
    accommodation: "5-star Hotel",
    customDetails: { "Visa Required": "On Arrival", "Language": "Arabic/English" },
    guestQuantity: { adultsMaxValue: 4, childrenMaxValue: 2, totalMaxValue: 6 },
    totalCapacity: 20,
    bookedCount: 3,
    freeCancellationDaysBefore: 14,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Tokyo & Kyoto Discovery",
    destination: "Tokyo",
    summary: "Blend the ultra-modern and the ancient — Tokyo's neon-lit streets, Mount Fuji views, and Kyoto's serene temples and geisha districts await you.",
    imageUrls: ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800"],
    rating: 4.9,
    reviewCount: 298,
    startDates: [new Date("2026-03-20"), new Date("2026-10-01"), new Date("2026-11-15")],
    durations: ["7 days", "10 days", "14 days"],
    pricePerDuration: { "7 days": "$1799", "10 days": "$2399", "14 days": "$3099" },
    mealPlans: ["BB", "HB"],
    mealSupplementsPerDay: { "HB": "$45" },
    tourType: "Cruises",
    hotelName: "Shinjuku Grand Hotel",
    hotelDescription: "Modern hotel in the heart of Tokyo with stunning city views.",
    accommodation: "4-star Hotel",
    customDetails: { "Visa Required": "Yes", "Language": "Japanese" },
    guestQuantity: { adultsMaxValue: 4, childrenMaxValue: 2, totalMaxValue: 6 },
    totalCapacity: 22,
    bookedCount: 15,
    freeCancellationDaysBefore: 14,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Santorini Sunset Cruise",
    destination: "Santorini",
    summary: "Experience the world-famous sunsets of Santorini, explore white-washed villages, black sand beaches, and ancient ruins of Akrotiri.",
    imageUrls: ["https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800"],
    rating: 4.8,
    reviewCount: 207,
    startDates: [new Date("2026-06-01"), new Date("2026-07-01"), new Date("2026-08-15")],
    durations: ["5 days", "7 days"],
    pricePerDuration: { "5 days": "$1299", "7 days": "$1699" },
    mealPlans: ["BB", "HB"],
    mealSupplementsPerDay: { "HB": "$40" },
    tourType: "Resorts",
    hotelName: "Caldera View Suites",
    hotelDescription: "Stunning cliffside hotel with infinity pools overlooking the caldera.",
    accommodation: "5-star Hotel",
    customDetails: { "Visa Required": "Schengen", "Language": "Greek" },
    guestQuantity: { adultsMaxValue: 2, childrenMaxValue: 1, totalMaxValue: 3 },
    totalCapacity: 18,
    bookedCount: 10,
    freeCancellationDaysBefore: 10,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "New York City Adventure",
    destination: "New York",
    summary: "The city that never sleeps — Times Square, Central Park, Statue of Liberty, Broadway shows, and world-class dining await in the Big Apple.",
    imageUrls: ["https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800"],
    rating: 4.6,
    reviewCount: 312,
    startDates: [new Date("2026-06-10"), new Date("2026-09-01"), new Date("2026-12-20")],
    durations: ["5 days", "7 days"],
    pricePerDuration: { "5 days": "$1099", "7 days": "$1499" },
    mealPlans: ["RO", "BB"],
    mealSupplementsPerDay: { "BB": "$25" },
    tourType: "Cruises",
    hotelName: "Manhattan Skyline Hotel",
    hotelDescription: "Contemporary hotel in Midtown Manhattan within walking distance of top attractions.",
    accommodation: "4-star Hotel",
    customDetails: { "Visa Required": "ESTA", "Language": "English" },
    guestQuantity: { adultsMaxValue: 4, childrenMaxValue: 2, totalMaxValue: 6 },
    totalCapacity: 35,
    bookedCount: 20,
    freeCancellationDaysBefore: 7,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Maldives Island Paradise",
    destination: "Maldives",
    summary: "Escape to the pristine turquoise waters of the Maldives. Overwater bungalows, snorkeling with manta rays, and total serenity.",
    imageUrls: ["https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800"],
    rating: 5.0,
    reviewCount: 95,
    startDates: [new Date("2026-07-01"), new Date("2026-10-15"), new Date("2026-12-01")],
    durations: ["5 days", "7 days", "10 days"],
    pricePerDuration: { "5 days": "$2499", "7 days": "$3299", "10 days": "$4499" },
    mealPlans: ["HB", "FB", "AI"],
    mealSupplementsPerDay: { "FB": "$60", "AI": "$110" },
    tourType: "Resorts",
    hotelName: "Azure Overwater Villas",
    hotelDescription: "Exclusive overwater bungalows with glass floors and direct lagoon access.",
    accommodation: "5-star Resort",
    customDetails: { "Visa Required": "On Arrival", "Language": "Dhivehi/English" },
    guestQuantity: { adultsMaxValue: 2, childrenMaxValue: 0, totalMaxValue: 2 },
    totalCapacity: 10,
    bookedCount: 4,
    freeCancellationDaysBefore: 21,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Safari in Kenya",
    destination: "Nairobi",
    summary: "Witness the Great Migration in Masai Mara, spot the Big Five, and experience authentic Maasai culture in Kenya's iconic savannah.",
    imageUrls: ["https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800"],
    rating: 4.9,
    reviewCount: 118,
    startDates: [new Date("2026-07-15"), new Date("2026-08-15"), new Date("2026-10-01")],
    durations: ["7 days", "10 days"],
    pricePerDuration: { "7 days": "$2299", "10 days": "$3099" },
    mealPlans: ["FB"],
    mealSupplementsPerDay: {},
    tourType: "Hikes",
    hotelName: "Masai Mara Tented Camp",
    hotelDescription: "Luxury tented camp on the edge of Masai Mara National Reserve.",
    accommodation: "Luxury Safari Camp",
    customDetails: { "Visa Required": "Yes", "Language": "Swahili/English", "Best Season": "July-October" },
    guestQuantity: { adultsMaxValue: 6, childrenMaxValue: 2, totalMaxValue: 8 },
    totalCapacity: 16,
    bookedCount: 6,
    freeCancellationDaysBefore: 30,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Barcelona & Costa Brava",
    destination: "Barcelona",
    summary: "Explore Gaudí's masterpieces, stroll La Rambla, relax on Costa Brava's golden beaches, and savour authentic tapas in vibrant Barcelona.",
    imageUrls: ["https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800"],
    rating: 4.7,
    reviewCount: 223,
    startDates: [new Date("2026-05-15"), new Date("2026-07-01"), new Date("2026-09-01")],
    durations: ["5 days", "7 days"],
    pricePerDuration: { "5 days": "$849", "7 days": "$1149" },
    mealPlans: ["BB", "HB"],
    mealSupplementsPerDay: { "HB": "$32" },
    tourType: "Resorts",
    hotelName: "Hotel Arts Barcelona",
    hotelDescription: "Iconic skyscraper hotel on the beachfront with panoramic Mediterranean views.",
    accommodation: "5-star Hotel",
    customDetails: { "Visa Required": "Schengen", "Language": "Spanish/Catalan" },
    guestQuantity: { adultsMaxValue: 4, childrenMaxValue: 2, totalMaxValue: 6 },
    totalCapacity: 28,
    bookedCount: 11,
    freeCancellationDaysBefore: 7,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Swiss Alps Adventure",
    destination: "Zurich",
    summary: "Ski the legendary slopes of Zermatt, cruise Lake Geneva, explore Lucerne's medieval charm and marvel at breathtaking Alpine scenery.",
    imageUrls: ["https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=800"],
    rating: 4.8,
    reviewCount: 156,
    startDates: [new Date("2026-12-10"), new Date("2027-01-10"), new Date("2027-02-10")],
    durations: ["5 days", "7 days", "10 days"],
    pricePerDuration: { "5 days": "$1799", "7 days": "$2399", "10 days": "$3199" },
    mealPlans: ["HB", "FB"],
    mealSupplementsPerDay: { "FB": "$55" },
    tourType: "Hikes",
    hotelName: "Zermatt Alpine Lodge",
    hotelDescription: "Cozy mountain lodge with Matterhorn views and direct ski-in/ski-out access.",
    accommodation: "4-star Chalet Hotel",
    customDetails: { "Visa Required": "Schengen", "Language": "German/French/Italian" },
    guestQuantity: { adultsMaxValue: 4, childrenMaxValue: 2, totalMaxValue: 6 },
    totalCapacity: 20,
    bookedCount: 7,
    freeCancellationDaysBefore: 14,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Rajasthan Royal Heritage Tour",
    destination: "Rajasthan",
    summary: "Travel through the land of maharajas — majestic forts, colourful bazaars, camel rides in the Thar Desert, and regal palace hotels in Jaipur, Jodhpur, and Udaipur.",
    imageUrls: ["https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800"],
    rating: 4.7,
    reviewCount: 184,
    startDates: [new Date("2026-10-15"), new Date("2026-11-15"), new Date("2027-01-20")],
    durations: ["7 days", "10 days"],
    pricePerDuration: { "7 days": "$899", "10 days": "$1249" },
    mealPlans: ["BB", "HB", "FB"],
    mealSupplementsPerDay: { "HB": "$20", "FB": "$38" },
    tourType: "Hikes",
    hotelName: "Umaid Bhawan Palace",
    hotelDescription: "A living palace and one of the world's greatest heritage hotels in Jodhpur.",
    accommodation: "Palace Hotel",
    customDetails: { "Visa Required": "Yes", "Language": "Hindi/Rajasthani", "Best Season": "Oct-Mar" },
    guestQuantity: { adultsMaxValue: 6, childrenMaxValue: 3, totalMaxValue: 9 },
    totalCapacity: 24,
    bookedCount: 9,
    freeCancellationDaysBefore: 10,
    assignedAgentId: null,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]);

print("✅ Successfully inserted " + db.tours.countDocuments() + " tours into the database!");

// ── Assign travel agents to tours ───────────────────────────────
const allTours = db.tours.find({}).toArray();
allTours.forEach((tour, idx) => {
  const agentId = agentIds[idx % agentIds.length].toString();
  db.tours.updateOne({ _id: tour._id }, { $set: { assignedAgentId: agentId } });
});
print("✅ Assigned travel agents to all tours (round-robin).");
